name: rhessys
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - pip
  - pip:
    - psutil==5.8.0
    - soupsieve==2.2
    - PyQt5_sip==4.19.18
    - msgpack==1.0.2
    - tqdm==4.57.0
    - async_generator==1.10
    - pandas==1.2.2
    - requests==2.25.1
    - partd==1.1.0
    - sortedcontainers==2.3.0
    - pycparser==2.20
    - zipfile2==0.0.12
    - bleach==3.3.0
    - argon2_cffi==20.1.0
    - sklearn==0.0
